name: Existing Pipeline

on:
  push:
    branches: [ main ]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Step One
        run: echo "This pipeline is from an existing YAML file"
      - name: Step Two
        run: echo "Second step in existing pipeline"
